Repository hackebrot/turtle, pull requests merged in 2020-05, with the labels that each got.

#11 start using go modules to main app as well as cli
  cmd/turtle/go.mod
  cmd/turtle/go.sum
  go.mod
  go.sum
Labels: dependencies

#15 Add lookup by emoji character 🕵️‍♂️
  CONTRIBUTORS.md
  cmd/turtle/char.go
  cmd/turtle/char_test.go
  cmd/turtle/turtle.go
  examples_test.go
  turtle.go
  turtle_test.go
Labels: enhancement

#16 Update test names 🤖
  cmd/turtle/category_test.go
  cmd/turtle/char_test.go
  cmd/turtle/keyword_test.go
  cmd/turtle/list_test.go
  cmd/turtle/search_test.go
  filters_test.go
  turtle_test.go
Labels: code quality

#4 Added a random command and plain option
  cmd/turtle/category.go
  cmd/turtle/keyword.go
  cmd/turtle/random.go
  cmd/turtle/search.go
  cmd/turtle/turtle.go
  cmd/turtle/writer.go
Labels: enhancement

#19 Make writer for JSON encoder configurable
  cmd/turtle/category.go
  cmd/turtle/category_test.go
  cmd/turtle/char.go
  cmd/turtle/char_test.go
  cmd/turtle/keyword.go
  cmd/turtle/keyword_test.go
  cmd/turtle/list.go
  cmd/turtle/list_test.go
  cmd/turtle/main.go
  cmd/turtle/random.go
  cmd/turtle/random_test.go
  cmd/turtle/search.go
  cmd/turtle/search_test.go
  cmd/turtle/testdata/category/animals_and_nature.json
  cmd/turtle/testdata/char/robot.json
  cmd/turtle/testdata/keyword/mountain.json
  cmd/turtle/testdata/list/categories.json
  cmd/turtle/testdata/list/help.txt
  cmd/turtle/testdata/search/dog.json
  cmd/turtle/testdata/search/rocket.json
  cmd/turtle/turtle.go
  cmd/turtle/turtle_test.go
  cmd/turtle/version.go
  go.sum
Labels: enhancement

#20 Use cobra version flag
  cmd/turtle/turtle.go
  cmd/turtle/turtle_test.go
  cmd/turtle/version.go
Labels: enhancement

#21 Improve positional arguments
  cmd/turtle/category.go
  cmd/turtle/char.go
  cmd/turtle/keyword.go
  cmd/turtle/list.go
  cmd/turtle/random.go
  cmd/turtle/search.go
  cmd/turtle/testdata/list/help.txt
  cmd/turtle/turtle.go
Labels: enhancement

#22 Add support for custom filters
  examples_test.go
  turtle.go
Labels: enhancement
